version: '3'
services:
  game-server:
    image: game-server
    build:
      context: ./game-server
      dockerfile: Dockerfile
    # networks:
    #   - backend
    ports:
      - "3000:3000"

  web3-backend:
    image: web3-backend
    build:
      context: ./web3-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # networks:
    #   - backend
# networks:
#   backend:
#     driver: bridge